name: Create release

on:
  workflow_dispatch:
    inputs:
      tagName:
        required: true
        type: string
      preRelease:
        required: true
        type: boolean
        default: false

jobs:
  build-all:
    uses: ./.github/workflows/msbuild.yml
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
  
  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:

    - name: download windows x64
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-build-win-x64

    - name: download windows x86
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-build-win-x86

    - name: download windows arm64
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-build-win-ARM64

    - name: download linux appimage
      uses: actions/download-artifact@v8
      with:
        skip-decompress: false
        name: voidsprite-build-linux-appimage-x64 

    - name: download linux flatpak
      uses: actions/download-artifact@v8
      with:
        skip-decompress: false
        name: voidsprite-build-linux64-flatpak-x86_64.flatpak

    - name: download mac
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-build-mac-universal

    - name: download android
      uses: actions/download-artifact@v8
      with:
        skip-decompress: false
        name: voidsprite-build-android

    - name: download emscripten
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-build-emscripten
    
    - name: download sdk
      uses: actions/download-artifact@v8
      with:
        skip-decompress: true
        name: voidsprite-sdk

    - name: create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ inputs.tagName }}
        release_name: Release ${{ inputs.tagName }}
        body: |
          Release generated by Actions
        draft: false
        prerelease: ${{ inputs.preRelease }}

    - name: upload windows x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-win-x64.zip
        asset_name: voidsprite-${{ inputs.tagName }}-win-x64.zip
        asset_content_type: application/zip
    - name: upload windows x86
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-win-x86.zip
        asset_name: voidsprite-${{ inputs.tagName }}-win-x86.zip
        asset_content_type: application/zip
    - name: upload windows ARM64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-win-ARM64.zip
        asset_name: voidsprite-${{ inputs.tagName }}-win-ARM64.zip
        asset_content_type: application/zip
    - name: upload android
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-release.apk
        asset_name: voidsprite-${{ inputs.tagName }}-android.apk
        asset_content_type: application/vnd.android.package-archive
    - name: upload linux appimage
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-latest-x86_64.AppImage
        asset_name: voidsprite-${{ inputs.tagName }}-linux-appimage-x64.AppImage
        asset_content_type: application/x-iso9660-appimage    
    - name: upload linux flatpak
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-linux64-flatpak.flatpak
        asset_name: voidsprite-${{ inputs.tagName }}-linux-flatpak-x64.flatpak
        asset_content_type: application/vnd.flatpak
    - name: upload mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-mac-universal.zip
        asset_name: voidsprite-${{ inputs.tagName }}-mac-universal.zip
        asset_content_type: application/zip
    - name: upload emscripten
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-build-emscripten.zip
        asset_name: voidsprite-${{ inputs.tagName }}-emscripten.zip
        asset_content_type: application/zip
    - name: upload sdk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./voidsprite-sdk.zip
        asset_name: voidsprite-${{ inputs.tagName }}-sdk.zip
        asset_content_type: application/zip
